version: '2'
services:
  vmware-exporter:
    # Using the latest tag, but you can use vers(v0.9.5 for example
    image: pryorda/vmware_exporter:latest
    volumes:
      - ./vmware_exporter/vmware_exporter.py:/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py
    hostname: vmware-exporter
    container_name: vmware-exporter
    ports:
        - "9275:9272"
    environment:
        VSPHERE_HOST: "10.94.5.201"
        VSPHERE_USER: "administrator@lqcs.iti.local"
        VSPHERE_PASSWORD: "ITI@LQps86"
        VSPHERE_IGNORE_SSL: "True"
        VSPHERE_COLLECT_VMS: "True"
        VSPHERE_FETCH_TAGS: "False"
        VSPHERE_FETCH_CUSTOM_ATTRIBUTES: "False"
        VSPHERE_COLLECT_VMGUESTS: "True"
        VSPHERE_COLLECT_HOSTS: "False"
        VSPHERE_COLLECT_SNAPSHOTS: "False"
        VSPHERE_COLLECT_DATASTORES: "False"
    restart: always
    #FOR DEBUG UNCOMMENT NEXT LINE
    command: ["-l","DEBUG"]
